### ISSUE TITLE
Build a subgraph in CFG for each function

### ISSUE THREAD

**Issue by x87** [x87/scout.js#3]
- a script file consists of one or more functions (main + each gosub)
- each function has its own subgraph in CFG
- isHeaderBlock property in basicBlocks is true for the first BB in a subgraph

**Comment by thelink2012** [comment]
Something to notice:
+ There are instances of `GOTO`s into `GOSUB` labels in a certain mission script in III I think.
+ `START_NEW_SCRIPT` and `LAUNCH_MISSION` should fit this nicely.
